### ISSUE TITLE
Building ONNX function from source

### ISSUE THREAD

**Issue by robinvanemden** [lsds/Faasm#130]
I am learning `Faasm` by rebuilding functions, but I am currently stumped on how to generate the `LLVM` `onnxruntime` include directory:

`/usr/local/faasm/llvm-sysroot/include/onnxruntime`

I presume I need to use `clang` to emit `LLVM IR` by compiling the OnnxRuntime source code? Do you maybe have a build script or `Makefile` that you could share, to help me get started?

**Comment by robinvanemden** [comment]
Now that I delve further into the code, I think that you are or will be replacing the ONNX function with a TensorFlow Lite one - am I correct? If so, would that be because the conversion of OnnxRuntime to WASM hampers its performance?

**Comment by Shillaker** [comment]
Hi Robin, thanks for the interest and sorry for the slow reply. Yes although I started experimenting with ONNX Runtime I had to abandon it as I couldn't get the latest version to compile to WebAssembly. I forgot to remove the ONNX function as part of the clean-up (have done so in the latest PR). The compilation fails when it hits the BLAS part. It looks like ONNX runtime only has BLAS for approved platforms and doesn't provide a generic unoptimized alternative. In the past they did have Eigen-only BLAS (via an option called `USE_EIGEN_FOR_BLAS`), but it was removed.

Tensorflow Lite on the other hand does have unoptimized BLAS and can be compiled to WebAssembly fairly easily. There are some docs on this here https://github.com/lsds/Faasm/blob/master/docs/tensorflow.md. Since I did that work they have actually added wasm support to Tensorflow.js too which could be interesting in future: https://yashints.dev/blog/2019/12/17/tfjs-wasm. 

There's an example TFLite function at https://github.com/lsds/Faasm/tree/master/func/tf. It uses Faasm's shared files to access the image and state for handling the model, so both of those need to be put in place before running it (also described in docs linked above). I made a couple of changes to it in the latest PR so make sure you've pulled from master.

Thanks again and let me know if you have any more issues.

**Comment by robinvanemden** [comment]
Hi Simon, thanks for your informative answer! Good to know about the BLAS related compilation problems with the ONNX Runtime. I may look into the compilation of some other inference engines that offer ONNX support, such as [MNN](https://github.com/alibaba/MNN) or [Menoh](https://github.com/pfnet-research/menoh). Yet it is already really cool to be able to run TFLite WASM functions! I will certainly play around with the tf function in the next few days and keep you posted if I encounter any issues, of course.

**Comment by prp** [comment]
Hi @robinvanemden it would be great if you could contribute back what you get to work as PRs, thanks.

**Comment by bhack** [comment]
Are you in contact with https://github.com/clang-ykt/ONNF?

**Comment by robinvanemden** [comment]
Thanks @bhack - looks interesting!

**Comment by bhack** [comment]
Check also https://groups.google.com/a/tensorflow.org/forum/m/#!topic/mlir/CUL3_8fnJb4
