### ISSUE TITLE
Getting started for newcomers

### ISSUE THREAD

**Issue by jiayihu** [lsds/Faasm#216]
Hi, I'm a CS student in Padova (Italy) on Master Degree and I was interested in working on a thesis about serverless computing and I found this project. I have personal good experience with JavaScript and frontend technologies, but I'm not sure where to get started with WebAssembly and this project in particular. Do you have any advice/resource to share?

I'd also love to see if you have any roadmap. I'm currently evaluating the idea of focusing the whole thesis on this cool stack Serverless on WASM and I'd like to help with some development hopefully, once I get my head around the technologies and the source code.

I opened an issue because others might be interested in contributing, serverless is an hot topic!
Thanks!

**Comment by mfournial** [comment]
Hi,
In terms of roadmap, it is currently quite HPC oriented at the moment. I'm currently doing my own thesis on using supporting existing OpenMP programs in a dynamic environment. And at the same time the codebase is being extended for MPI support and is being corrected for WASI compatibility instead of the current more custom Faasm host interface.

There are many new things you could use Faasm for to give you a head start. If you're a JS developer your could look at https://github.com/Shillaker/faasmjs and tune Faasm for edge computing workloads for example. If you're interested in graphics processing, the OpenMP API is currently adding support for GPUs but nobody is looking at how to integrate this with WebAssembly (see my failed PoC #197 - getting this to work would be great). I have a dream that the current integration with Rust will be extended with Rust futures in a super composable API efficiently ran by building computational DAGs internally but you'd have to be a wizard to get this to work.

**Comment by jiayihu** [comment]
Thanks for the reply. Yup, after I posted the issue I found the paper about Faasm and realised it's focused on HPC whereas my interest is more on edge computing and replicating/analysing the work done by Fastly and Cloudflare. 
I'm also interested in the integration with Rust, but I didn't understand your statement about composable API with DAGs. I suppose I need to study a lot yet :)

**Comment by Shillaker** [comment]
Hi @jiayihu, thanks for the interest! 

If you're coming from the browser/ Javascript world then you might be interested in the cross-over between client-side wasm and server-side wasm as @mfournial mentioned. Faasm.js was a PoC I did to experiment with offloading client-side wasm tasks to a back-end serverless wasm cluster. The idea is to have exactly the same code able to execute in the browser and on the server so that the runtime or user can choose where it gets run, potentially making the decision dynamically. A client-side library could choose to offload work to a serverless back-end to access a much higher level of parallelism, or to execute code closer to large datasets stored in the cloud (e.g. for video/ image processing). This is essentially a standard client-server model, so isn't really that interesting in itself, but there's potential in looking at the programming model when you have a uniform client-server execution environment, and when/ how you dynamically offload work to other devices. It could also be interesting to extend this to other execution environments such as phones or IoT/ embedded devices, creating a sea of computing power, all able to execute the same code. Taking that idea a step further, you could also think about volunteer computing, offering a wasm-capable device or browser up to join part of a larger cluster of things all working collectively to solve problems.

Faasm provides a good base for this sort of project, as it offers lightweight isolation, low overheads and distributed shared state. That said, our current focus is indeed on larger distributed computation, trying to push the limits of the system in terms of parallelism and performance. This focus will only only cover the next few months, and I'd still be interested to hear any more concrete thoughts/ proposals you come up with.

Hope at least some of that has been useful/ triggered some potential ideas!
