### ISSUE TITLE
Read a file in python

### ISSUE THREAD

**Issue by nayakajay** [lsds/Faasm#239]
I have a simple program that tries to read a file in python
 ```
with open(path, 'r') as f:
    content = f.read()
```

The problem I am facing is the path, even though I give the absolute path
eg. /usr/local/code/faasm/my_data.json
[I have added the file in the environment, just copied it though, which can be the problem]

I found only 1 sample for reading a file in python [bench_telco.py], however the file was present in dist-packages folder.

These are the steps I have done so far:

[copy my_data.json to Faasm home folder]
1. ./bin/cli.sh
2. cp my_data.json /tmp/
3. Launch a function to read this file, This results in **FileNotFOundError**

Should I do something similar to what **bench_telco.py** does?

**Comment by Shillaker** [comment]
Hi @nayakajay , because Faasm is a multi-tenant runtime, it stops functions from accessing arbitrary files on the underlying host for security purposes. While certain files can be whiltelisted (e.g. those related to the Python runtime), all others must go through Faasm's shared file support. 

Generally it is inadvisable to share data using the filesystem if you can avoid it, and instead use Faasm's state. The role of a filesystem in a serverless environment is unclear and platform-specific, hence using some external storage or state is preferable (IMHO).

If you do wish to access files from your functions, you can first upload the file, then use the relative path prefixed with `faasm://`inside the function, i.e.:

- Upload the shared file using the [shared files API](https://github.com/lsds/Faasm/blob/master/docs/api.md#shared-files) (specifying some relative path e.g. `aaa/bbb`)
- Open the file in code by prefixing this path with `faasm://` (e.g. `faasm://aaa/bbb`)

**Comment by nayakajay** [comment]
Yes, I agree with the role of the filesystem in a serverless environment is unclear as it potentially opens up other security concerns as well. 
I was using a file to replace an http request for fetching data and see the behavior.
I have tried the API and it works as expected.

Thanks, closing this issue now.
