### ISSUE TITLE
Adding custom packages to faasm

### ISSUE THREAD

**Issue by nayakajay** [lsds/faasm#241]
I want to add a custom package to faasm, so that I can use it in my functions.
I cloned pyodide repo in third-party/pyodide folder as it was empty?

I will use boto3 as the running example
```
cd faasm_home
source workon.sh
./bin/pyodide mkpkg boto3 # this creates a meta.yml
./bin/pyodide buildpkg --package_abi=0 packages/boto3/meta.yaml
```

I don't see any errors yet.
Next step is to modify tasks/python.py
I take this is file is present in faasmcli/faasmcli
I add it to the dictionary as explained, similar to other modules but with proper version

Next step
```
inv python.set-up-package
```

It says 'inv' command not found. Here is where I am wondering if this has to be done after running
./bin/cli.sh.

I tried that, and it generated machine code.
On running a simple python file that uses boto3, it shows, No module named boto3

I am not sure which step is wrong over here or are there some inconsistencies in the documentation.

**Comment by nayakajay** [comment]
Few Updates:

1. I saw that the for pyodide you have a different fork, I got that up and running
2. All the steps mentioned here ["https://github.com/lsds/Faasm/blob/master/docs/python.md"](url)
from **Building CPython** till **Adding the new package to the runtime root** have to be performed post
```
./bin/cli.sh
```
3. I have achieved codegen step and it's all successful. But still get some error
![Error_6_boto3](https://user-images.githubusercontent.com/35248326/80945598-c3db4b00-8e09-11ea-8422-91813f8a60ae.png)

**Comment by mfournial** [comment]
If I remember correctly `boto3` is used in the CLI commands. It looks like you're trying to develop locally so make sure you follow the steps in (the local dev)[https://github.com/lsds/Faasm/blob/master/docs/local_dev.md), or at least the bits relevant to python. Here you're missing
```
cd faasm_home
pip install -r faasmcli/requirements.txt
```

**Comment by Shillaker** [comment]
Hi @nayakajay first off, you're right that Faasm uses a custom Pyodide fork, this is handled using Git submodules, which guarantee the repo is pinned to a specific commit. `third-party/pyodide` will be empty if you haven't updated these Git submodules, which you can do by running `git submodule update --init third-party/pyodide` (more docs [here](https://git-scm.com/book/en/v2/Git-Tools-Submodules). This is left out of the normal container set-up as the submodules are not needed for runtime execution.

While Faasm and Pyodide can technically run arbitrary packages, the feasibility of this will depend on the underlying runtime. Faasm functions run inside Faasm, and Pyodide code normally runs in a browser, neither of which are "normal" POSIX-like environments, hence will not provide normal filesystem or networking support. Faasm's filesystem support is limited to "global read local write", with functions being isolated from the underlying host filesystem (which is where you've run into issues with #239). This is discussed briefly in the [host interface docs](https://github.com/lsds/Faasm/blob/master/docs/host_interface.md#posix-like-calls-and-wasi). Networking support is equally limited. As a result, I can't guarantee that `boto3` will operate as normal even if we do solve your issue.

What you're seeing is down to using the containerised Faasm environment:

- You're compiling CPython and setting up `boto3` in the CLI container (where it's getting set up in `/usr/local/faasm/runtime_root`)
- You're executing the function in the `worker` container, which is a different container, hence has its own virtual filesystem, and can't "see" the `boto3` files
- To share the relevant files between containers, you can try setting up a shared volume on `/usr/local/faasm/runtime_root` directory, just like we already have with `/usr/local/faasm/object` 

I would usually recommend doing this level of development with the [local dev setup](https://github.com/lsds/Faasm/blob/master/docs/local_dev.md) rather than in containers as it avoids such issues. 

Can I ask what you're aiming to achieve? Perhaps I can give some pointers and avoid any wasted effort if the end goal is ultimately unfeasible.

**Comment by nayakajay** [comment]
I have a bunch of functions with usage of nltk, boto3, tensorflow and few other packages. I would like to use them in faasm environment. I was trying to add them to the environment one by one. 
However, I get your point when you mentioned can't "see", makes sense to me now.

For local dev setup, I am not sure if i want to change Faasm code yet, however I would like to add more packages.

So to achieve this, I don't have to **build cpython from scratch**?
Just the **Adding new package to environment root**?

To create a shared volume, is there any documentation I can follow?

**Comment by Shillaker** [comment]
I would be surprised if an application combining those packages will work in Faasm/ Pyodide without a _lot_ of work. Every Python package requires effort to port to Pyodide, especially if it uses a lot of C bindings. Tensorflow has some fairly heavyweight C/C++ code which must be compiled to WebAssembly, and will introduce further native dependencies that also need to be compiled to WebAssembly. As an experiment I would run `strace` on your existing application and see which system calls it uses and which libraries it links dynamically. Any system calls not currently supported by Faasm and WASI will need to be added, and any dynamically linked libraries will need to be ported too (native libraries and Python C bindings). This should give you an indication of the scale of the task ahead.

You can probably get away with porting pure Python libraries without compiling CPython from scratch, but to build any libraries that have C bindings you'll need to link against the compiled WebAssembly CPython. 

Docker volumes are a standard feature and amenable to Googling (e.g. https://docs.docker.com/storage/volumes/).
